---
title: "Clasificación de imágenes con Redes Neuronales"
output: html_notebook
---

# Librerias aplicadas

```{r}
library(caret)
library(raster)
```

# Carga de las bandas de imágenes satelitales.

```{r}
band1 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B1.TIF")
band2 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B2.TIF")
band3 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B3.TIF")
band4 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B4.TIF")
band5 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B5.TIF")
band6 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B6.TIF")
band7 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B7.TIF")
band10 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B10.TIF")
band11 <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/capturas-landsat/roma/LC81910312013208LGN00/LC81910312013208LGN00_B11.TIF")

roma_rst_lan <- brick(band1,band2,band3,band4,band5,band6,band7,band10,band11)
names(roma_rst_lan) <- c(paste("Banda",1:7,sep=""),"Banda10","Banda11")
```

# Procesado de datos

```{r}
#Carga de muestras de entrenamiento
rstTrainroma <- raster("/Users/elianaalizchuquillanquijulcapari/Documents/workspace-r/demos/DataTraining/rome_lcz_GT.tif")

# Remover ceros (fondo NA)
rstTrainroma[rstTrainroma==0] <- NA

# Convertir a tipo discreto
rstTrainroma <- ratify(rstTrainroma)

# Cambiamos el nombre
names(rstTrainroma) <- "layer"

#Muestras de valores
table(values(rstTrainroma))

# Eliminación de NAs 
rstDFlanroma.df <- na.omit(values(stack(rstTrainroma, roma_rst_lan)))

# Viualizamos las muestras
cols <- c("#fde725","#b5de2b", "#6ece58","#35b779", "#1f9e89","#26828e", "#31688e", "#3e4989", "#482878", "#440154")
plot(rstTrainroma, main="Muestras de entrenamiento de Roma", col = cols)

```

# Fase de Clasificación

```{r}
#Si es la primera vez se ejecuta, sino ya esta guardado los datos del dataframe.
write.csv(rstDFlanroma.df,"rstDFRoma.csv", row.names = FALSE)

#Leemos los datos
samplesLanroma = read.csv("rstDFRoma.csv")

# Se divide las muestras en 70 y 30
trainx = list(0)
evalx = list(0)
for (i in 1:17){ # se itera en todas las posibles categorías
  cls = samplesLanroma[samplesLanroma$layer == i,]
  smpl <- floor(0.70 * nrow(cls))
  tt <- sample(seq_len(nrow(cls)), size = smpl)
  trainx[[i]] <- cls[tt,]
  evalx[[i]] <- cls[-tt,]
}


# Se combina en dataframe referenciados s entrenamiento y evaluación
trn = do.call(rbind, trainx) 
eva = do.call(rbind, evalx)
```

# Algoritmo Redes neuronales

```{r}
# Definiendo el control del entrenamiento
fitControl2 <- trainControl(method = "cv",
                           number = 10) 


# Entrenamiento con Redes Neuronales
nnet_grid <- expand.grid(size = c(5, 10, 15),
                         decay = c(0.001, 0.01, 0.1))

nnet_model1 <- caret::train(x = trn[,(2:ncol(trn))], y = as.factor(trn$layer),
                               method = "nnet", metric="Accuracy", 
                               maxit = 100,
                               tuneGrid = nnet_grid,
                               preProcess = c("center", "scale"),
                               trControl = fitControl2,
                               trace = FALSE)

nnet_grid2 = expand.grid(size = seq(from = 2, to = 10, by = 2), 
                        decay = seq(from = 0.1, to = 0.5, by = 0.1))

nnet_model2 <- caret::train(x = trn[,(2:ncol(trn))], y = as.factor(trn$layer),
                               method = "nnet", metric="Accuracy",
                               maxit = 100,
                               tuneGrid = nnet_grid2,
                               preProcess = c("center", "scale"),
                               trControl = fitControl2,
                               trace = FALSE)

```

# Estructura de la red

```{r}
library(NeuralNetTools)
plotnet(nnet_model1$finalModel)

#modelo 2
plotnet(nnet_model2$finalModel)
```

# Exploración del modelo

```{r}
#Información modelo nnet
print(nnet_model1)

print(nnet_model2)

#Gráfica del modelo nnet
plot(nnet_model1)

plot(nnet_model2)
```

# Evaluación del modelo 1.

```{r}
pred_nnet_model1<- predict(nnet_model1,
                              newdata = eva)

cm <- confusionMatrix(data = pred_nnet_model1, as.factor(eva$layer))
cm
```

# Matriz de confusión modelo 1

```{r}

cm_d <- as.data.frame(cm$table)

cm_st <-data.frame(cm$overall)

cm_st$cm.overall <- round(cm_st$cm.overall,2)

cm_p <- as.data.frame(prop.table(cm$table))
cm_d$Perc <- round(cm_p$Freq*100,2)

# dibujando la matriz
ggplot(data = cm_d, aes(x = Prediction , y =  Reference, fill = Freq))+
  geom_tile(color = "white", lwd = 0.5) +
  geom_text(aes(label = paste("",Freq)), color = 'white', size = 3.5)+ 
  theme_minimal() +
  ggtitle("Matriz de Confusión")
```

# Evaluación del modelo 2

```{r}
pred_nnet_model2<- predict(nnet_model2,
                              newdata = eva)

cm <- confusionMatrix(data = pred_nnet_model2, as.factor(eva$layer))
cm
```

# Matriz de confusión modelo 2

```{r}
cm_d <- as.data.frame(cm$table)

cm_st <-data.frame(cm$overall)

cm_st$cm.overall <- round(cm_st$cm.overall,2)

cm_p <- as.data.frame(prop.table(cm$table))
cm_d$Perc <- round(cm_p$Freq*100,2)

# dibujando la matriz
ggplot(data = cm_d, aes(x = Prediction , y =  Reference, fill = Freq))+
  geom_tile(color = "white", lwd = 0.5) +
  geom_text(aes(label = paste("",Freq)), color = 'white', size = 3.5)+ 
  theme_minimal() +
  ggtitle("Matriz de Confusión")
```

# Predicción y visualización Modelo 1.

```{r}
classi_nnet_model1 <- raster::predict(roma_rst_lan, model=nnet_model1)
plot(classi_nnet_model1, main="Clasificación Redes neuronales Modelo 1",col = cols)
```

# Predicción y visualización Modelo 2.

```{r}
classi_nnet_model2 <- raster::predict(roma_rst_lan, model=nnet_model2)
plot(classi_nnet_model2, main="Clasificación Redes neuronales Modelo 2", col = cols)
```

